# Generated by Django 3.1.5 on 2021-01-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=500)),
                ('requirements_json_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('prereqs', models.ManyToManyField(related_name='_course_prereqs_+', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.CharField(max_length=2)),
                ('current_courses', models.ManyToManyField(related_name='current_courses', to='courses.Course')),
                ('past_courses', models.ManyToManyField(related_name='past_courses', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('webpage', models.CharField(max_length=200)),
                ('requirements', models.ManyToManyField(to='courses.Achievment')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_members', models.ManyToManyField(to='courses.User')),
            ],
        ),
    ]
